
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'MMDrawerController', '~> 0.5.7'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Parse'
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseModel'
pod 'LayerKit'
pod 'SVProgressHUD'
pod 'Atlas'