
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'MMDrawerController'
pod 'FBSDKCoreKit', '4.5.0'
pod 'FBSDKLoginKit', '4.5.0'
pod 'FBSDKShareKit', '4.5.0'
pod 'Parse' 
pod 'ParseUI'
pod 'ParseFacebookUtilsV4'
pod 'ParseTwitterUtils'
pod 'ParseModel'
pod 'LayerKit'
pod 'SVProgressHUD'
pod 'Atlas'
pod 'InstagramKit', '~> 3.0'
pod "TTRangeSlider"
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'GoogleAppIndexing'
pod 'APTimeZones'